-- MySQL Script generated by MySQL Workbench
-- Mon Feb  1 06:40:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_bancario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_bancario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_bancario` DEFAULT CHARACTER SET utf8 ;
USE `db_bancario` ;

-- -----------------------------------------------------
-- Table `db_bancario`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bancario`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bancario`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bancario`.`tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bancario`.`cuenta_bancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bancario`.`cuenta_bancaria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` INT NULL,
  `fecha` DATE NULL,
  `concepto` VARCHAR(255) NULL,
  `tipo_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `tipo_id_idx` (`tipo_id` ASC),
  CONSTRAINT `tipo_id`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `db_bancario`.`tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bancario`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bancario`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `cuenta_id` INT NULL,
  `rol_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `cuenta_id_idx` (`cuenta_id` ASC),
  INDEX `rol_id_idx` (`rol_id` ASC),
  CONSTRAINT `rol_id`
    FOREIGN KEY (`rol_id`)
    REFERENCES `db_bancario`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cuenta_id`
    FOREIGN KEY (`cuenta_id`)
    REFERENCES `db_bancario`.`cuenta_bancaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
